name: Tests y Calificación Automática

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout del código
      uses: actions/checkout@v3
      
    - name: Configurar Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        cache: 'npm'
        
    - name: Instalar dependencias
      run: npm install
      
    - name: Ejecutar tests
      run: npm test
      
    - name: Generar reporte de cobertura
      run: npm run test:coverage
      continue-on-error: true
      
    - name: Mostrar estadísticas
      run: |
        echo "Tests completados"
        echo "Revisa los resultados arriba para ver tu calificación"
        
    - name: ¡Felicidades!
      if: success()
      run: |
        echo "¡Excelente trabajo! Todos los tests pasaron correctamente."
        echo "Tu código está listo para ser calificado."
